# Generated by Django 2.2.7 on 2020-01-25 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abcd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_education', models.CharField(max_length=30)),
                ('board', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('job_name', models.CharField(max_length=50)),
                ('job_profile', models.TextField()),
                ('job_salary', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('Job_summary', models.TextField(default='abc')),
                ('job_responsibilities', models.TextField(default='abc')),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cate_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Key_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('name_candidate', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
                ('education', models.ManyToManyField(blank=True, to='crm.Education')),
                ('job_expriance', models.ManyToManyField(blank=True, to='crm.Job')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.State')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Job_category'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_company_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_keyskills',
            field=models.ManyToManyField(default='COMPUTER', to='crm.Key_skills'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Job_type'),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.State'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Company_type'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.State'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
