# Generated by Django 2.2.7 on 2020-01-25 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company_type',
            old_name='company_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job_category',
            old_name='job_cate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job_type',
            old_name='job_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='key_skills',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name_state',
            new_name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.State'),
        ),
        migrations.AddField(
            model_name='company',
            name='GST',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Wholeseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('name', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('GST', models.CharField(default='', max_length=20)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
                ('company_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Company_type')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.State')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31)),
                ('name', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=50)),
                ('GST', models.CharField(default='', max_length=20)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Area')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
                ('company_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.Company_type')),
                ('state', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.State')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
