# Generated by Django 2.2.7 on 2020-01-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
