# Generated by Django 3.0.2 on 2020-01-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
